import { z } from 'zod';
import { PhoneNumberSchema } from './phoneNumbers.js';

export const PersonSchema = z
    .object({
        Id: z.number(),
        IdKey: z.string(),
        Guid: z.string(),
        IsSystem: z.boolean(),
        RecordTypeValueId: z.number(),
        RecordStatusValueId: z.number(),
        RecordStatusLastModifiedDateTime: z.string().nullable(),
        RecordStatusReasonValueId: z.number().nullable(),
        ConnectionStatusValueId: z.number(),
        IsDeceased: z.boolean(),
        TitleValueId: z.number().nullable(),
        FirstName: z.string().nullable(),
        LastName: z.string().nullable(),
        MiddleName: z.string().nullable(),
        NickName: z.string().nullable(),
        FullName: z.string().nullable(),
        SuffixValueId: z.number().nullable(),
        PhotoId: z.number().nullable(),
        BirthDay: z.number().nullable(),
        BirthMonth: z.number().nullable(),
        BirthYear: z.number().nullable(),
        Age: z.number().nullable(),
        Gender: z.number().nullable(),
        MaritalStatusValueId: z.number().nullable(),
        AnniversaryDate: z.string().nullable(),
        GivingId: z.string().nullable(),
        GivingLeaderId: z.number().nullable(),
        GivingGroupId: z.number().nullable(),
        Email: z.string().nullable(),
        IsEmailActive: z.boolean(),
        EmailNote: z.string().nullable(),
        EmailPreference: z.number().nullable(),
        CommunicationPreference: z.number().nullable(),
        AgeClassification: z.number().nullable(),
        PrimaryFamilyId: z.number().nullable(),
        IsLockedAsChild: z.boolean(),
        DeceasedDate: z.string().nullable(),
        AccountProtectionProfile: z.number().nullable(),
        BirthDateKey: z.number().nullable(),
        PrimaryAliasId: z.number().nullable(),
        PrimaryAliasGuid: z.string().nullable(),
        PhoneNumbers: z.array(PhoneNumberSchema),
        BirthDate: z.string().nullable(),
        CreatedDateTime: z.string().nullable(),
        ModifiedDateTime: z.string().nullable(),
        CreatedByPersonAliasId: z.number().nullable(),
        ModifiedByPersonAliasId: z.number().nullable(),
    })
    .catchall(z.any()); // Allow additional properties
