import { PhoneNumber } from './phoneNumbers.js';

export interface Person {
    Id: number;
    IdKey: string;
    Guid: string;
    IsSystem: boolean;
    RecordTypeValueId: number;
    RecordStatusValueId: number;
    RecordStatusLastModifiedDateTime: string | null;
    RecordStatusReasonValueId: number | null;
    ConnectionStatusValueId: number;
    IsDeceased: boolean;
    TitleValueId: number | null;
    FirstName: string | null;
    LastName: string | null;
    MiddleName: string | null;
    NickName: string | null;
    FullName: string | null;
    SuffixValueId: number | null;
    PhotoId: number | null;
    BirthDay: number | null;
    BirthMonth: number | null;
    BirthYear: number | null;
    Age: number | null;
    Gender: number | null;
    MaritalStatusValueId: number | null;
    AnniversaryDate: string | null;
    GraduationYear: number | null;
    GivingId: string | null;
    GivingLeaderId: number | null;
    GivingGroupId: number | null;
    Email: string | null;
    IsEmailActive: boolean;
    EmailNote: string | null;
    EmailPreference: number | null;
    CommunicationPreference: number | null;
    ReviewReasonNote: string | null;
    InactiveReasonNote: string | null;
    SystemNote: string | null;
    ViewedCount: number | null;
    TopSignalColor: string | null;
    TopSignalIconCssClass: string | null;
    TopSignalId: number | null;
    AgeClassification: number | null;
    PrimaryFamilyId: number | null;
    PrimaryCampusId: number | null;
    IsLockedAsChild: boolean;
    DeceasedDate: string | null;
    ContributionFinancialAccountId: number | null;
    AccountProtectionProfile: number | null;
    PreferredLanguageValueId: number | null;
    ReminderCount: number | null;
    RaceValueId: number | null;
    EthnicityValueId: number | null;
    BirthDateKey: number | null;
    AgeBracket: number | null;
    FirstNamePronunciationOverride: string | null;
    NickNamePronunciationOverride: string | null;
    LastNamePronunciationOverride: string | null;
    PronunciationNote: string | null;
    PrimaryAliasId: number | null;
    PrimaryAliasGuid: string | null;
    IsChatProfilePublic: boolean | null;
    IsChatOpenDirectMessageAllowed: boolean | null;
    PhoneNumbers: PhoneNumber[];
    DaysUntilBirthday: number | null;
    Initials: string | null;
    BirthdayDayOfWeek: string | null;
    BirthdayDayOfWeekShort: string | null;
    BirthDate: string | null;
    NextBirthDay: string | null;
    DaysToBirthdayOrNull: number | null;
    DaysToBirthday: number | null;
    DaysToAnniversary: number | null;
    DaysToAnniversaryOrNull: number | null;
    NextAnniversary: string | null;
    DaysUntilAnniversary: number | null;
    GradeOffset: number | null;
    HasGraduated: boolean | null;
    GradeFormatted: string | null;
    CreatedDateTime: string | null;
    ModifiedDateTime: string | null;
    CreatedByPersonAliasId: number | null;
    ModifiedByPersonAliasId: number | null;
    ModifiedAuditValuesAlreadyUpdated: boolean;
    ForeignId: number | null;
    ForeignGuid: string | null;
    ForeignKey: string | null;
    [key: string]: any; // Allow additional properties
}
