import { PhoneNumber } from './phoneNumbers.js';

export interface Person {
    Id: number;
    IdKey: string;
    Guid: string;
    IsSystem: boolean;
    RecordTypeValueId: number;
    RecordStatusValueId: number;
    RecordStatusLastModifiedDateTime: string | null;
    RecordStatusReasonValueId: number | null;
    ConnectionStatusValueId: number;
    IsDeceased: boolean;
    TitleValueId: number | null;
    FirstName: string | null;
    LastName: string | null;
    MiddleName: string | null;
    NickName: string | null;
    FullName: string | null;
    SuffixValueId: number | null;
    PhotoId: number | null;
    BirthDay: number | null;
    BirthMonth: number | null;
    BirthYear: number | null;
    Age: number | null;
    Gender: number | null;
    MaritalStatusValueId: number | null;
    AnniversaryDate: string | null;
    GivingId: string | null;
    GivingLeaderId: number | null;
    GivingGroupId: number | null;
    Email: string | null;
    IsEmailActive: boolean;
    EmailNote: string | null;
    EmailPreference: number | null;
    CommunicationPreference: number | null;
    AgeClassification: number | null;
    PrimaryFamilyId: number | null;
    IsLockedAsChild: boolean;
    DeceasedDate: string | null;
    AccountProtectionProfile: number | null;
    BirthDateKey: number | null;
    PrimaryAliasId: number | null;
    PrimaryAliasGuid: string | null;
    PhoneNumbers: PhoneNumber[];
    BirthDate: string | null;
    CreatedDateTime: string | null;
    ModifiedDateTime: string | null;
    CreatedByPersonAliasId: number | null;
    ModifiedByPersonAliasId: number | null;
    [key: string]: any; // Allow additional properties
}
